const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);const scoreEl=$('score'),bestEl=$('best'),startScreen=$('startScreen'),overScreen=$('gameOverScreen'),winScreen=$('winScreen'),hint=$('hint');
let W=0,H=0,dpr=1,last=0,playing=false,over=false,holding=false,sound=true,audio=null,levelIndex=0,score=0,distance=0,particles=[],trail=[];
let best=Number(localStorage.getItem('waveBest'))||0;bestEl.textContent=best;
const LEVELS=[
{name:'FIRST SIGNAL',difficulty:'EASY',speed:210,length:4200,gap:250,amp:50,freq:.0042,obstacles:.10,color:'#6fffe9'},
{name:'PULSE',difficulty:'EASY+',speed:235,length:4700,gap:225,amp:70,freq:.0048,obstacles:.16,color:'#72d7ff'},
{name:'DRIFT',difficulty:'MEDIUM',speed:260,length:5200,gap:205,amp:90,freq:.0054,obstacles:.22,color:'#8d9cff'},
{name:'VOLT',difficulty:'MEDIUM+',speed:285,length:5700,gap:185,amp:105,freq:.0060,obstacles:.29,color:'#bd7cff'},
{name:'NOVA',difficulty:'HARD',speed:315,length:6200,gap:165,amp:120,freq:.0067,obstacles:.36,color:'#ff73cf'},
{name:'RIFT',difficulty:'HARD+',speed:345,length:6700,gap:150,amp:135,freq:.0074,obstacles:.43,color:'#ff7189'},
{name:'VOID',difficulty:'EXTREME',speed:375,length:7200,gap:138,amp:150,freq:.0082,obstacles:.50,color:'#ff9d5c'},
{name:'OVERDRIVE',difficulty:'INSANE',speed:410,length:7800,gap:126,amp:165,freq:.0090,obstacles:.58,color:'#ffe66f'}
];
const ship={x:0,y:0,vy:0,r:9};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function lvl(){return LEVELS[levelIndex]}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ship.x=Math.max(90,W*.18);if(!playing)ship.y=H/2}addEventListener('resize',resize,{passive:true});
function levelStars(i){return '◆'.repeat(Math.min(5,1+Math.floor(i/2)))}
function buildMenu(){const g=$('levelGrid');g.innerHTML='';LEVELS.forEach((l,i)=>{const b=document.createElement('button');b.className='level-card';b.style.setProperty('--accent',l.color);b.innerHTML=`<span class="stars">${levelStars(i)}</span><span class="level-no">${String(i+1).padStart(2,'0')}</span><span class="level-name">${l.name}</span><span class="difficulty">${l.difficulty}</span>`;b.onclick=()=>startLevel(i);g.appendChild(b)})}
function startLevel(i){levelIndex=i;score=0;distance=0;particles=[];trail=[];over=false;holding=false;ship.x=Math.max(90,W*.18);ship.y=H/2;ship.vy=0;playing=true;startScreen.classList.remove('active');overScreen.classList.remove('active');winScreen.classList.remove('active');scoreEl.textContent='0';$('levelHud').textContent=`LEVEL ${String(i+1).padStart(2,'0')} · ${lvl().name}`;$('progressHud').textContent='0%';hint.classList.add('show');setTimeout(()=>hint.classList.remove('show'),1700);last=performance.now();beep(520,.06)}
function showLevels(){playing=false;over=false;holding=false;overScreen.classList.remove('active');winScreen.classList.remove('active');startScreen.classList.add('active')}
function centerAt(worldX){const l=lvl();const base=H/2;const a=Math.sin(worldX*l.freq)*l.amp;const b=Math.sin(worldX*l.freq*.43+1.7)*l.amp*.42;const c=Math.sin(worldX*l.freq*1.83+.4)*l.amp*.16;return base+a+b+c}
function gapAt(worldX){const l=lvl();return l.gap*(.94+.06*Math.sin(worldX*.0021+2))}
function obstacleAt(worldX){const l=lvl();const cell=340;const n=Math.floor(worldX/cell);const hash=Math.abs(Math.sin(n*91.733+levelIndex*17.17)*43758.5453)%1;if(hash>l.obstacles)return null;const x=n*cell+cell*.68;const center=centerAt(x),gap=gapAt(x),side=(Math.sin(n*17.31)>0)?1:-1;return{x,y:center+side*(gap*.29),r:13+levelIndex*.7}}
function beep(f,d){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){}}
function update(dt){if(!playing)return;const l=lvl();distance+=l.speed*dt;const accel=holding?-760:760;ship.vy+=accel*dt;ship.vy=clamp(ship.vy,-310-levelIndex*8,310+levelIndex*8);ship.y+=ship.vy*dt;trail.push({x:ship.x,y:ship.y,a:1});if(trail.length>24)trail.shift();const wx=distance+ship.x,center=centerAt(wx),gap=gapAt(wx),top=center-gap/2,bottom=center+gap/2;if(ship.y-ship.r<top||ship.y+ship.r>bottom){end();return}const start=Math.floor((wx-50)/340)-1,endCell=Math.floor((wx+50)/340)+1;for(let n=start;n<=endCell;n++){const ob=obstacleAt(n*340+170);if(!ob)continue;const ox=ob.x-distance;if(Math.hypot(ship.x-ox,ship.y-ob.y)<ship.r+ob.r){end();return}}score=Math.floor(distance/12)+(levelIndex+1)*25;scoreEl.textContent=score;const p=clamp(distance/l.length,0,1);$('progressHud').textContent=Math.floor(p*100)+'%';if(distance>=l.length)complete()}
function end(){playing=false;over=true;holding=false;const isBest=score>best;if(isBest){best=score;localStorage.setItem('waveBest',best)}bestEl.textContent=best;$('finalScore').textContent=score;$('finalBest').textContent=best;$('finalProgress').textContent=Math.floor(clamp(distance/lvl().length,0,1)*100)+'%';$('newBest').classList.toggle('show',isBest);overScreen.classList.add('active');burst(ship.x,ship.y,28);beep(110,.24)}
function complete(){playing=false;holding=false;if(score>best){best=score;localStorage.setItem('waveBest',best);bestEl.textContent=best}$('winScore').textContent=score;$('nextBtn').textContent=levelIndex===LEVELS.length-1?'PLAY AGAIN ↻':'NEXT LEVEL →';winScreen.classList.add('active');burst(ship.x,ship.y,42);beep(760,.18)}
function burst(x,y,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*240,vy:(Math.random()-.5)*240,a:1})}
function drawGrid(){ctx.strokeStyle='#ffffff07';ctx.lineWidth=1;const off=-(distance*.18%70);for(let x=off;x<W;x+=70){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=70){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function drawTunnel(){const l=lvl(),step=12;ctx.save();ctx.shadowBlur=16;ctx.shadowColor=l.color;ctx.strokeStyle=l.color;ctx.lineWidth=3;for(const side of[-1,1]){ctx.beginPath();for(let x=-step;x<=W+step;x+=step){const wx=distance+x,c=centerAt(wx),g=gapAt(wx),y=c+side*g/2;x===-step?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke()}ctx.shadowBlur=0;ctx.globalAlpha=.12;ctx.fillStyle=l.color;ctx.beginPath();ctx.moveTo(0,0);for(let x=0;x<=W;x+=step){const wx=distance+x;ctx.lineTo(x,centerAt(wx)-gapAt(wx)/2)}ctx.lineTo(W,0);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W;x+=step){const wx=distance+x;ctx.lineTo(x,centerAt(wx)+gapAt(wx)/2)}ctx.lineTo(W,H);ctx.closePath();ctx.fill();ctx.restore()}
function drawObstacles(){const l=lvl();for(let x=-100;x<W+150;x+=40){const wx=distance+x,ob=obstacleAt(wx);if(!ob)continue;const sx=ob.x-distance;if(sx<-40||sx>W+40)continue;ctx.save();ctx.translate(sx,ob.y);ctx.rotate(distance*.006);ctx.shadowBlur=20;ctx.shadowColor=l.color;ctx.strokeStyle=l.color;ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<4;i++){const a=Math.PI/4+i*Math.PI/2,r=ob.r;const px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.stroke();ctx.restore()}}
function drawShip(){const c=lvl().color;trail.forEach((t,i)=>{ctx.beginPath();ctx.arc(t.x,t.y,1.5+i*.12,0,7);ctx.fillStyle=`${c}${Math.floor(i/trail.length*70).toString(16).padStart(2,'0')}`;ctx.fill()});ctx.save();ctx.translate(ship.x,ship.y);const ang=clamp(ship.vy/500,-.55,.55);ctx.rotate(ang);ctx.shadowBlur=24;ctx.shadowColor=c;ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-9,-8);ctx.lineTo(-4,0);ctx.lineTo(-9,8);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(3,-2,2.2,0,7);ctx.fill();ctx.restore()}
function drawPortal(){const x=lvl().length-distance;if(x>W+80||x<-80)return;const c=lvl().color;ctx.save();ctx.translate(x,H/2);ctx.strokeStyle=c;ctx.shadowBlur=28;ctx.shadowColor=c;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,46,0,7);ctx.stroke();ctx.globalAlpha=.3;ctx.lineWidth=12;ctx.beginPath();ctx.arc(0,0,34,0,7);ctx.stroke();ctx.restore()}
function drawParticles(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.a-=dt*1.8;ctx.fillStyle=`rgba(111,255,233,${Math.max(0,p.a)})`;ctx.fillRect(p.x,p.y,3,3)});particles=particles.filter(p=>p.a>0)}
function loop(t){const dt=Math.min((t-last)/1000,.025)||0;last=t;ctx.clearRect(0,0,W,H);drawGrid();if(playing)update(dt);drawTunnel();drawObstacles();drawPortal();drawShip();drawParticles(dt);requestAnimationFrame(loop)}
function press(e){if(e)e.preventDefault();if(!playing)return;holding=true}function release(e){if(e)e.preventDefault();holding=false}
addEventListener('keydown',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)){if(!e.repeat)press(e)}});addEventListener('keyup',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code))release(e)});canvas.addEventListener('pointerdown',press);addEventListener('pointerup',release);addEventListener('pointercancel',release);addEventListener('blur',()=>holding=false);
$('restartBtn').onclick=()=>startLevel(levelIndex);$('levelsBtn').onclick=showLevels;$('winLevelsBtn').onclick=showLevels;$('nextBtn').onclick=()=>startLevel(levelIndex===LEVELS.length-1?0:levelIndex+1);$('soundBtn').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'♪':'×'};
resize();buildMenu();requestAnimationFrame(loop);