const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);const scoreEl=$('score'),bestEl=$('best'),startScreen=$('startScreen'),overScreen=$('gameOverScreen'),winScreen=$('winScreen'),hint=$('hint');
let W=0,H=0,dpr=1,last=0,playing=false,paused=false,holding=false,sound=true,audio=null,levelIndex=0,score=0,distance=0,particles=[],trail=[],course=null;
let best=Number(localStorage.getItem('waveBest'))||0;bestEl.textContent=best;
const LEVELS=[
{name:'FIRST SIGNAL',difficulty:'EASY',speed:235,length:5200,gap:285,turn:75,spikes:.12,gears:.04,color:'#6fffe9'},
{name:'PULSE',difficulty:'EASY+',speed:250,length:5700,gap:260,turn:90,spikes:.16,gears:.06,color:'#72d7ff'},
{name:'DRIFT',difficulty:'MEDIUM',speed:270,length:6200,gap:235,turn:105,spikes:.21,gears:.08,color:'#8d9cff'},
{name:'VOLT',difficulty:'MEDIUM+',speed:290,length:6700,gap:215,turn:118,spikes:.26,gears:.10,color:'#bd7cff'},
{name:'NOVA',difficulty:'HARD',speed:315,length:7200,gap:195,turn:130,spikes:.31,gears:.13,color:'#ff73cf'},
{name:'RIFT',difficulty:'HARD+',speed:340,length:7700,gap:178,turn:142,spikes:.36,gears:.16,color:'#ff7189'},
{name:'VOID',difficulty:'EXTREME',speed:365,length:8200,gap:162,turn:152,spikes:.42,gears:.19,color:'#ff9d5c'},
{name:'OVERDRIVE',difficulty:'INSANE',speed:395,length:8800,gap:148,turn:162,spikes:.48,gears:.22,color:'#ffe66f'}];
const ship={x:0,y:0,vy:0,r:8};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lvl=()=>LEVELS[levelIndex];
function rand(seed){const x=Math.sin(seed*127.1+levelIndex*311.7)*43758.5453;return x-Math.floor(x)}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ship.x=Math.max(105,W*.2);if(!playing)ship.y=H/2}addEventListener('resize',resize,{passive:true});
function levelStars(i){return '◆'.repeat(Math.min(5,1+Math.floor(i/2)))}
function buildMenu(){const g=$('levelGrid');g.innerHTML='';LEVELS.forEach((l,i)=>{const b=document.createElement('button');b.className='level-card';b.style.setProperty('--accent',l.color);b.innerHTML=`<span class="stars">${levelStars(i)}</span><span class="level-no">${String(i+1).padStart(2,'0')}</span><span class="level-name">${l.name}</span><span class="difficulty">${l.difficulty}</span>`;b.onclick=()=>startLevel(i);g.appendChild(b)})}
function buildCourse(){const l=lvl(),seg=170-levelIndex*5,pts=[];let x=-400,y=H/2,dir=0;pts.push({x,y});while(x<l.length+W+500){x+=seg;const r=rand(Math.floor(x/seg));if(x<650)dir=0;else if(r<.28)dir=-1;else if(r<.56)dir=1;else if(r<.76)dir=0;const margin=l.gap/2+55;let ny=y+dir*l.turn;if(ny<margin){ny=margin;dir=1}if(ny>H-margin){ny=H-margin;dir=-1}pts.push({x,y:ny});y=ny}const hazards=[];for(let i=5;i<pts.length-3;i++){const a=pts[i],b=pts[i+1],r=rand(i+73);if(r<l.gears){const x=(a.x+b.x)/2,y=(a.y+b.y)/2+(rand(i+91)>.5?1:-1)*l.gap*.18;hazards.push({type:'gear',x,y,r:18+levelIndex*.7,rot:rand(i)*6.28})}else if(r<l.gears+l.spikes){const side=rand(i+27)>.5?1:-1;hazards.push({type:'spike',x:a.x+(b.x-a.x)*.55,side,size:20+levelIndex*.8})}}course={pts,hazards,seg}}
function centerAt(x){const p=course.pts;if(x<=p[0].x)return p[0].y;for(let i=0;i<p.length-1;i++){if(x<=p[i+1].x){const a=p[i],b=p[i+1],t=(x-a.x)/(b.x-a.x);return a.y+(b.y-a.y)*t}}return p[p.length-1].y}
function startLevel(i){levelIndex=i;score=0;distance=0;particles=[];trail=[];holding=false;paused=false;ship.x=Math.max(105,W*.2);ship.y=H/2;ship.vy=0;buildCourse();playing=true;startScreen.classList.remove('active');overScreen.classList.remove('active');winScreen.classList.remove('active');scoreEl.textContent='0';$('levelHud').textContent=`LEVEL ${String(i+1).padStart(2,'0')} · ${lvl().name}`;$('progressHud').textContent='0%';hint.classList.add('show');setTimeout(()=>hint.classList.remove('show'),1600);last=performance.now();beep(520,.06)}
function showLevels(){playing=false;paused=false;holding=false;overScreen.classList.remove('active');winScreen.classList.remove('active');startScreen.classList.add('active')}
function beep(f,d){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type='triangle';g.gain.setValueAtTime(.028,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){}}
function spikeTriangle(h){const l=lvl(),cx=centerAt(h.x),wall=cx+h.side*l.gap/2,tip=wall-h.side*h.size*1.75;return[{x:h.x-h.size,y:wall},{x:h.x,y:tip},{x:h.x+h.size,y:wall}]}
function pointInTri(px,py,a,b,c){const s=(p1,p2,p3)=>(p1.x-p3.x)*(p2.y-p3.y)-(p2.x-p3.x)*(p1.y-p3.y);const p={x:px,y:py},d1=s(p,a,b),d2=s(p,b,c),d3=s(p,c,a),neg=d1<0||d2<0||d3<0,pos=d1>0||d2>0||d3>0;return !(neg&&pos)}
function collideHazards(wx){for(const h of course.hazards){if(Math.abs(h.x-wx)>55)continue;if(h.type==='gear'){if(Math.hypot(wx-h.x,ship.y-h.y)<ship.r+h.r*.82)return true}else{const t=spikeTriangle(h);if(pointInTri(wx,ship.y,t[0],t[1],t[2])||pointInTri(wx,ship.y-ship.r,t[0],t[1],t[2])||pointInTri(wx,ship.y+ship.r,t[0],t[1],t[2]))return true}}return false}
function update(dt){if(!playing||paused)return;const l=lvl();distance+=l.speed*dt;/* Space-Waves-style control: thrust builds upward velocity; release quickly bends the arrow downward. */const target=holding?-(235+levelIndex*8):(235+levelIndex*8),response=holding?11:13;ship.vy+=(target-ship.vy)*Math.min(1,response*dt);ship.y+=ship.vy*dt;trail.push({x:ship.x,y:ship.y});if(trail.length>42)trail.shift();const wx=distance+ship.x,c=centerAt(wx),top=c-l.gap/2,bottom=c+l.gap/2;if(ship.y-ship.r<=top||ship.y+ship.r>=bottom||ship.y<0||ship.y>H||collideHazards(wx)){end();return}score=Math.floor(distance/10)+(levelIndex+1)*30;scoreEl.textContent=score;const p=clamp(distance/l.length,0,1);$('progressHud').textContent=Math.floor(p*100)+'%';if(distance>=l.length)complete()}
function end(){playing=false;holding=false;const isBest=score>best;if(isBest){best=score;localStorage.setItem('waveBest',best)}bestEl.textContent=best;$('finalScore').textContent=score;$('finalBest').textContent=best;$('finalProgress').textContent=Math.floor(clamp(distance/lvl().length,0,1)*100)+'%';$('newBest').classList.toggle('show',isBest);overScreen.classList.add('active');burst(ship.x,ship.y,32);beep(105,.25)}
function complete(){playing=false;holding=false;if(score>best){best=score;localStorage.setItem('waveBest',best);bestEl.textContent=best}$('winScore').textContent=score;$('nextBtn').textContent=levelIndex===LEVELS.length-1?'PLAY AGAIN ↻':'NEXT LEVEL →';winScreen.classList.add('active');burst(ship.x,ship.y,46);beep(780,.2)}
function burst(x,y,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.5)*260,a:1})}
function drawGrid(){ctx.strokeStyle='#ffffff07';ctx.lineWidth=1;const off=-(distance*.25%64);for(let x=off;x<W;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function drawTunnel(){if(!course)return;const l=lvl(),c=l.color,visible=course.pts.map(p=>({x:p.x-distance,y:p.y}));ctx.save();ctx.lineJoin='miter';ctx.lineCap='square';ctx.strokeStyle=c;ctx.shadowColor=c;ctx.shadowBlur=14;ctx.lineWidth=3;for(const side of[-1,1]){ctx.beginPath();let started=false;for(const p of visible){if(p.x<-300||p.x>W+300)continue;const y=p.y+side*l.gap/2;if(!started){ctx.moveTo(p.x,y);started=true}else ctx.lineTo(p.x,y)}ctx.stroke()}ctx.shadowBlur=0;ctx.globalAlpha=.12;ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(-10,0);for(const p of visible)if(p.x>-300&&p.x<W+300)ctx.lineTo(p.x,p.y-l.gap/2);ctx.lineTo(W+10,0);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(-10,H);for(const p of visible)if(p.x>-300&&p.x<W+300)ctx.lineTo(p.x,p.y+l.gap/2);ctx.lineTo(W+10,H);ctx.closePath();ctx.fill();ctx.restore()}
function drawGear(h){const x=h.x-distance;if(x<-50||x>W+50)return;const c=lvl().color,n=12,r=h.r;ctx.save();ctx.translate(x,h.y);ctx.rotate(h.rot+distance*.012);ctx.strokeStyle=c;ctx.fillStyle='#0a0e1d';ctx.lineWidth=3;ctx.shadowBlur=16;ctx.shadowColor=c;ctx.beginPath();for(let i=0;i<n*2;i++){const a=i*Math.PI/n,rr=i%2?r*1.32:r*.9,px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,r*.38,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawHazards(){if(!course)return;const c=lvl().color;ctx.save();ctx.fillStyle=c;ctx.shadowBlur=12;ctx.shadowColor=c;for(const h of course.hazards){if(h.type==='gear'){drawGear(h);continue}const x=h.x-distance;if(x<-50||x>W+50)continue;const t=spikeTriangle(h);ctx.beginPath();ctx.moveTo(t[0].x-distance,t[0].y);ctx.lineTo(t[1].x-distance,t[1].y);ctx.lineTo(t[2].x-distance,t[2].y);ctx.closePath();ctx.fill()}ctx.restore()}
function drawShip(){const c=lvl().color,angle=Math.atan2(ship.vy,lvl().speed);ctx.save();ctx.strokeStyle=c;ctx.lineWidth=2;ctx.globalAlpha=.35;ctx.beginPath();trail.forEach((t,i)=>i?ctx.lineTo(t.x,t.y):ctx.moveTo(t.x,t.y));ctx.stroke();ctx.globalAlpha=1;ctx.translate(ship.x,ship.y);ctx.rotate(angle);ctx.shadowBlur=25;ctx.shadowColor=c;ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-10,-9);ctx.lineTo(-4,0);ctx.lineTo(-10,9);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(-4,-3);ctx.lineTo(-1,0);ctx.lineTo(-4,3);ctx.closePath();ctx.fill();ctx.restore()}
function drawPortal(){if(!course)return;const x=lvl().length-distance;if(x>W+80||x<-80)return;const c=lvl().color,y=centerAt(lvl().length);ctx.save();ctx.translate(x,y);ctx.strokeStyle=c;ctx.shadowBlur=28;ctx.shadowColor=c;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,lvl().gap*.27,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawParticles(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.a-=dt*1.8;ctx.fillStyle=`rgba(111,255,233,${Math.max(0,p.a)})`;ctx.fillRect(p.x,p.y,3,3)});particles=particles.filter(p=>p.a>0)}
function drawPause(){if(!paused)return;ctx.fillStyle='#050711aa';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='800 34px Inter';ctx.fillText('PAUSED',W/2,H/2)}
function loop(t){const dt=Math.min((t-last)/1000,.025)||0;last=t;ctx.clearRect(0,0,W,H);drawGrid();if(playing)update(dt);drawTunnel();drawHazards();drawPortal();drawShip();drawParticles(dt);drawPause();requestAnimationFrame(loop)}
function press(e){if(e)e.preventDefault();if(playing&&!paused)holding=true}function release(e){if(e)e.preventDefault();holding=false}
addEventListener('keydown',e=>{if(e.code==='KeyP'&&playing){paused=!paused;holding=false;return}if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();if(playing&&!paused)holding=true;else if(!playing&&overScreen.classList.contains('active'))startLevel(levelIndex)}});addEventListener('keyup',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();holding=false}});canvas.addEventListener('pointerdown',press);addEventListener('pointerup',release);addEventListener('pointercancel',release);addEventListener('blur',()=>holding=false);
$('restartBtn').onclick=()=>startLevel(levelIndex);$('levelsBtn').onclick=showLevels;$('winLevelsBtn').onclick=showLevels;$('nextBtn').onclick=()=>startLevel(levelIndex===LEVELS.length-1?0:levelIndex+1);$('soundBtn').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'♪':'×'};
resize();buildMenu();buildCourse();requestAnimationFrame(loop);